networks:
  super_network:
    driver: bridge
services:
  app: 
    container_name: fnITLab2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - super_network
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: StudentsData
    ports:
      - "5433:5432"
    networks:
      - super_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: